### PR TITLE
Lab01branch

### PR DESCRIPTION
**Pull request by DemondBoone**

### CODE REVIEW

**Review by justin-young5 — CHANGES_REQUESTED** [review]
version 2 of lab returned a 0 answer for 'ft' values, expected a value not zero

**Review by justin-young5 — CHANGES_REQUESTED** [review]
lab2ver1 returns numbers separated by commas as the translation
45 returns forty, five, correct answer is forty-five

**Comment by DemondBoone** [comment]
Updated version 2

**Review by violette-git — APPROVED** [review]
Great work. Unit converter meets lab requirements.

**Pull request merged**
