### PR TITLE
too easy, drill sergeant!

### PR DESCRIPTION
**Pull request by roverbay**

### CODE REVIEW

**Review by justin-young5 — CHANGES_REQUESTED** [review]
There is a version 2 on this lab, make sure you include it on this branch.

**Review by violette-git — CHANGES_REQUESTED** [review]
Lab 2 requires you be able to search the api and return a list of quotes for the given. search term. There shouldn't be too many changes to what you already have. 

Let me know if you need help.

**Review by justin-young5 — CHANGES_REQUESTED** [review]
The lab is wanting you to return the entire page of quotes should be 25 per page for a specific keyword.  Then ask the user if they want to view next page or done, if next page the print the 25 quotes for that page and prompt the user again.  Ask if you need any help.

**Review by justin-young5 — APPROVED** [review]
Works well, good job.  Lab complete.

**Pull request merged**
